apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/grafana-dashboardDefinitions.yaml
- ./manifests/kubePrometheus-prometheusRule.yaml
- ./manifests/kubeStateMetrics-prometheusRule.yaml
- ./manifests/kubernetesControlPlane-prometheusRule.yaml
- ./manifests/nodeExporter-prometheusRule.yaml
